# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.1'
prepare_react_native_project!

setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
   'Camera',
   'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
   'MediaLibrary',
  # 'Microphone',
  # 'Motion',
   'Notifications',
   'PhotoLibrary',
   'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Frontend' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      
      # Convert OTHER_CFLAGS to array if it's a string
      flags = config.build_settings['OTHER_CFLAGS']
      if flags.is_a?(String)
        flags = flags.split(' ')  # Split string into array by spaces
      elsif flags.nil?
        flags = []
      end

      # Remove unwanted flags if any
      flags.reject! { |flag| flag.include?('-Wno-shorten-64-to-32-Wdeprecated-declarations') }

      # Add the needed flag if not present
      flags << '-Wdeprecated-declarations' unless flags.include?('-Wdeprecated-declarations')

      # Assign back as array
      config.build_settings['OTHER_CFLAGS'] = flags

      # Repeat for C++ flags
      cpp_flags = config.build_settings['OTHER_CPLUSPLUSFLAGS']
      if cpp_flags.is_a?(String)
        cpp_flags = cpp_flags.split(' ')
      elsif cpp_flags.nil?
        cpp_flags = []
      end

      cpp_flags.reject! { |flag| flag.include?('-Wno-shorten-64-to-32-Wdeprecated-declarations') }
      cpp_flags << '-Wdeprecated-declarations' unless cpp_flags.include?('-Wdeprecated-declarations')
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cpp_flags
    end
  end
end
end 
