# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.1'
prepare_react_native_project!

setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
   'Camera',
   'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
   'MediaLibrary',
  # 'Microphone',
  # 'Motion',
   'Notifications',
   'PhotoLibrary',
   'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Frontend' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']

      # Fix malformed warning flag
      if config.build_settings['OTHER_CFLAGS'].is_a?(Array)
        config.build_settings['OTHER_CFLAGS'].map! do |flag|
          flag.gsub('-Wno-shorten-64-to-32-Wno-deprecated-declarations', '-Wno-shorten-64-to-32 -Wno-deprecated-declarations')
        end
      elsif config.build_settings['OTHER_CFLAGS'].is_a?(String)
        config.build_settings['OTHER_CFLAGS'] = config.build_settings['OTHER_CFLAGS']
          .gsub('-Wno-shorten-64-to-32-Wno-deprecated-declarations', '-Wno-shorten-64-to-32 -Wno-deprecated-declarations')
      end

      # Add safe flags (in case not already included)
      config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations' unless config.build_settings['OTHER_CFLAGS'].include?('-Wno-deprecated-declarations')
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-deprecated-declarations' unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].include?('-Wno-deprecated-declarations')
    end
  end
end

end 