name: QuickChat-frontend CI/CD

on:
  push:
    branches:
      # - main
      - registration-encryption
      
jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  build-android:
    needs: [lint-and-test]
    uses: ./.github/workflows/build-android.yml
    secrets:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  build-ios:
    needs: [lint-and-test]
    uses: ./.github/workflows/build-ios.yml
